### ISSUE TITLE
Changing the default operator

### ISSUE THREAD

**Issue by sasaki77** [sasaki77/archiverappliance-datasource#143]
@klauer, @slacAWallace

I noticed that [you have discussed the changing the default operator](https://github.com/pcdshub/archiverappliance-datasource/pull/1).
Is there any progress on this?

I don't think `raw` is not suitable for all users, but a customizable default operator is promising.
Changing it on the data source settings page is one candidate.

I'm considering implementing the select option on the data source settings page to change the default operator.

The settings page will look like the following image:

![Pasted image 20230331163649](https://user-images.githubusercontent.com/6987021/229060350-f2b4533c-7225-4c5c-9e0c-51636a8df80e.png)

Does this implementation meet your requirement?
Any comments are welcome.

**Comment by klauer** [comment]
Hi @sasaki77, thanks for bringing this up!

I agree that 'raw' is probably not the best default for most.
I think that your proposed solution of having the default operator be configurable in the data source settings makes a lot of sense 👍 

This change request by @slacawallace came out of an issue that we encountered with alerting when using non-raw operators with stale data. If I recall correctly it was something like (for example): data was last updated in the archiver yesterday, panel alert time frame set to last 5 minutes, which then resulted in a 'no data' condition and led to many alerts. However that's a different discussion that we should open a separate issue for (ping @tangkong - want to make a new issue in this repo?)

**Comment by slacAWallace** [comment]
Hi @sasaki77 I like your proposed solution.

It is as @klauer says, the inciting incident(s) was a torrent of alert messages coming from no-data conditions.

It's not yet clear to us if it's because of a timeout stemming from an overloaded archiver or something in-between or an issue with the query that the plugin forms or with how the response is handled. I had mistakenly thought (prematurely) that it was due to the mean vs. raw or last operator being chosen. I no longer believe this is the issue.

In any case I think we would elect to have our default operator probably be raw, last or lastFill. Being able to elect what the default will be for us is great!
