### ISSUE TITLE
Release 1.3.2 flagged as Trojan

### ISSUE THREAD

**Issue by bennettopaul** [sasaki77/archiverappliance-datasource#57]
Windows security has flagged the plugin as Trojan:MacOS/Botnet.B!MTB.

**Comment by sasaki77** [comment]
I can't reproduce this. Could you give me more information like below?

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Grafana Server**
- OS:
- Grafana version:

**Grafana Client**
- OS:
- Browser:
- Browser version:

**Anti-virus Software**
- Software: [e.g. Windows defender, Avast]
- Version:

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Comment by bennettopaul** [comment]
Hi,

Sorry about the late reply. This slipped my mind. This is reproducible in Edge and Chrome, but not Firefox. When downloading https://github.com/sasaki77/archiverappliance-datasource/releases/download/1.3.2/archiverappliance-datasource.zip. 


Windows security immediately flags it as a Trojan:MacOS/Botnet.B!MTB.

>archiverappliance-datasource/dist/gpx_archiver-datasource-backend_darwin_amd64

This is just the stock Windows Defender antivirus. The source download is not affected.

This is on Windows 10 Enterprise x64, Version 20H2, Build 19042.1165

Cheers,
Paul

**Comment by sasaki77** [comment]
Thank you for giving information. I understood your situation.
Unfortunately, I can't reproduce this because I use ESET as Anti-virus software and it doesn't flag it.

`gpx_archiver-datasource-backend_darwin_amd64` is for Mac OS. So I don't think there's major problem to run the plugin on Windows OS.

Have you tried to run the plugin?

I hope you can ignore this flag for a while.  I'm not sure I can correct this, but I'll take it into account on next release.

By the way, we've tested for Linux OS only. If there're any problem on Windows, please let me know.

**Comment by klauer** [comment]
May be worth taking a look at virustotal - it'll scan the binaries with multiple engines.

**Comment by sasaki77** [comment]
I'm not sure the reason, but virustotal currently doesn't flag the file as Trojan from v1.3.3. I'm closing the issue for now. Please reopen the issue if there are any problems.
